language: python
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install:
  - travis_retry pip install .
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install pep8 pyflakes
  - travis_retry pip install -e git+https://github.com/peteut/nose2-cprof.git#egg=nose2cprof
# command to run tests
script:
  - pyflakes elex_lite
  - pep8 elex_lite
  - pyflakes tests
  - pep8 tests
  - python -m nose2.__main__ -v
sudo: false
